baseURL = "https://design2.com"
languageCode = "en-us"
title = "eMobileCampus"
publishDir = "tfinch97.github.io"

# The site's parameters
[params]
  home = "Home"
  
  [menu]
    [[menu.header]]
      weight = 4
      name = "Services"
      url = "service"
    [[menu.header]]
      weight = 5
      name = "Contact"
      url = "contact"

    
    [[menu.footer]]
      weight = 2
      name = "Contact us"
      url = "contact"
    [[menu.footer]]
      weight = 5
      name = "Terms"
      url = "wrapper.html"

  [params.slider]
    enable = true
    title = "eMobileCampus™ is a cloud infrastructure company"
    subtitle = "We provide cloud computing for institutions of higher learning, businesses and non profits."
    bgImage = "img/slider-bg.jpg"
    btnText = "Discover Our Services"
    url = "service"

  [params.wrapper]
    enable = true
    image = "img/wrapper-img.png"
    title = "About Us"
    italic = "eMobileCampus offers best of class Cloud solutions to colleges, universities, organizations of all types who want to leverage the benefits of the Cloud but don’t have the budget to build out and support their own data center.   Our solutions are designed to affordably expand your abilities.  We offer a broad set of solutions and services to help you design, build and manage your infrastructure."
    paragraph = "With over 40 years experience in IT infrastructure support, the founders at eMobileCampus (formerly H.E.Y Consulting LLC) have chosen to not only provide the highest quality infrastructure and expertise, but also the most personal service in the market today."

  [params.blog]
    enable = false
    title = "View What Other Have Said"
    subtitle = "Testimonies from our customers"

  [params.feature]
    enable = true
    title = "We believe in great ideas"
    bgImage = "img/feature-bg.jpg"
    content = "eMobileCampus offers best of class Cloud solutions to colleges, universities, organizations of all types who want to leverage the benefits of the Cloud but don’t have the budget to build out and support their own data center.   Our solutions are designed to affordably expand your abilities.  We offer a broad set of solutions and services to help you design, build and manage your infrastructure."
    [params.feature.button]
      caption = "View Services"
      url = "service"

  [params.call]
    enable = true
    bgImage = "img/call-to-action-bg.jpg"
    title = "Do you need expertise but lack the resources or capacity?"
    paragraph = "Whether you need the Cloud for off-site data storage, business continuity planning, or as stable primary infrastructure, eMobileCampus Cloud solutions can be customized to fit any of your needs. If you’re investigating your options, whether you need hosting, design, deployment or management services, send us a message or call."
    [params.call.button]
      url = "contact"
      text = "Send us a message"

  [params.contact]
    enable = true
    title = "Drop us a note or call"
    subtitle = "Don’t just take our word for it. Check out some of the testimonies from our customers."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "240 Skyline Dr., Ste. 2090, Conway, AR 72032"
      email = "Email: info@emobilecampus.com"
      phone = "Call Ken - Phone: (877) 439-3262 or (501) 765-0505"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"

